//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream brass_1 {
            get {
                return ResourceManager.GetStream("brass_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream brass_2 {
            get {
                return ResourceManager.GetStream("brass_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream elixia_organ {
            get {
                return ResourceManager.GetStream("elixia_organ", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream flute {
            get {
                return ResourceManager.GetStream("flute", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream flute_low {
            get {
                return ResourceManager.GetStream("flute_low", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream guitar_1 {
            get {
                return ResourceManager.GetStream("guitar_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream guitar_2 {
            get {
                return ResourceManager.GetStream("guitar_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream harp {
            get {
                return ResourceManager.GetStream("harp", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream oboe {
            get {
                return ResourceManager.GetStream("oboe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P = 0
        ///LA = 441
        ///LAG = LA/2
        ///LAH = 2*LA
        ///LAHH = 4*LA
        ///SOLG1 = LAG*99/112
        ///SOLG = LAG*8/9
        ///SOLG3 = SOLG*896/891
        ///SOLGD1 =SOLG1*2187/2048
        ///SOLGD = LAG*243/256
        ///SOLGD3 = LAG*21/22
        ///SOLGDD1 = SOLGD1*2187/2048
        ///SOLGDD = SOLGD*2187/2048
        ///SOLGDD3 = SOLGD3*2187/2048
        ///LAGBB1 = SOLG1*524288/531441
        ///LAGBB = SOLG*524288/531441
        ///LAGBB3 = SOLG3*524288/531441
        ///LAGB1 = LAG*176/189
        ///LAGB = LAG*2048/2187
        ///LAGB3  = SOLG3*256/243
        ///LAG1 = LAG*891/896
        ///LAG3 = LAG*896/891
        ///LAGD1 = LAG1*2187/2048
        ///LAGD = LAG*2187/2048
        ///LAGD3 = LAG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string occidental_scale {
            get {
                return ResourceManager.GetString("occidental_scale", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream organ {
            get {
                return ResourceManager.GetStream("organ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P = 0
        ///LA = 441
        ///LAG = LA/2
        ///LAH = 2*LA
        ///LAHH = 4*LA
        ///SOLG1 = LAG*99/112
        ///SOLG = LAG*8/9
        ///SOLG3 = SOLG*896/891
        ///SOLGB1 = SOLG*176/189
        ///SOLGBQ1 = SOLG*15/14
        ///SOLGBQM1 = SOLG1*15/14
        ///SOLGD1 =SOLG1*2187/2048
        ///SOLGD = LAG*243/256
        ///SOLGSD1B = LAG*891/896*10/11
        ///SOLGSD1H = LAG*891/896*14/15
        ///SOLGD3 = LAG*21/22
        ///SOLGSD2B = LAG*29/32
        ///SOLGSD2H = LAG*27/29
        ///SOLGDQ3 = LAG*20/21
        ///SOLGDQ2 = LAG*891/896*20/21
        ///LAGBQ1 = SOLG*21/20
        ///LAGBQM1 = SOLG1*21/20
        ///LAGBQ2 = SOLG3*21/20
        ///LAGSB1B = SOLG*15/14
        ///LAGSB1H = SOLG*11/10
        ///L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oriental_scale {
            get {
                return ResourceManager.GetString("oriental_scale", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream oud {
            get {
                return ResourceManager.GetStream("oud", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream oud_tremolo {
            get {
                return ResourceManager.GetStream("oud_tremolo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream piano_2 {
            get {
                return ResourceManager.GetStream("piano_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream piano_3 {
            get {
                return ResourceManager.GetStream("piano_3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream string_0 {
            get {
                return ResourceManager.GetStream("string_0", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream string_1 {
            get {
                return ResourceManager.GetStream("string_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream string_2 {
            get {
                return ResourceManager.GetStream("string_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream violin {
            get {
                return ResourceManager.GetStream("violin", resourceCulture);
            }
        }
    }
}
